import Head from "next/head";
import { useState } from "react";
import InputForm from "../components/input-form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Newsletter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center w-1/2 mx-auto pt-20 sm:w-4/5">
        <h1 className="text-3xl text-yellow-500 font-bold">Sign up to my Newsletter!</h1>
        <InputForm />
      </main>
    </div>
  );
}
